### ISSUE TITLE
Add multi connection support

### ISSUE THREAD

**Issue by stefliekens** [tailrdigital/sulu-translations-bundle#3]
With multi doctrine connection support you can push new translations to a remote database and pull them afterwards and save them in your git project repository. 

**Considerations:**
What about doctrine migration files? 

**Idea:** 
Rework the provider and rename to `tailr_translations` instead of `database`. The `dsn` contains the Doctrine DBAL connection name. By default it has will be `default`. 
```
framework:
    translator:
        providers:
            tailr_translations:
                dsn: 'tailr_translations://custom_dbal_connection_here'
                domains: [ 'messages' ]
                locales: [ 'nl', 'en', 'fr' ]
```

**Tasks:**
- Creating a "setup" command for creating database table with provide db table schema in PHP (see example in \Symfony\Component\Messenger\Bridge\Doctrine\Transport\Connection::setup, messenger:setup-transport)
- Rework (Doctrine) repository using configured DBAL connection
- Rework \Tailr\SuluTranslationsBundle\Presentation\Controller\Admin\ListController for bypassing Sulu ORM code: implement your own query/criteria which can be used for feeding the PaginatedRepresentation. 
- Rework or add "list" query for \Tailr\SuluTranslationsBundle\Infrastructure\Symfony\Translation\Provider\Loader::generateMessageCatalogue. Maybe the query/criteria can be used after refactoring the ListController
- Update documentation
